name: Publish on GitHub Pages 

on: 
  push: 
    branches: [ main ]

permissions: 
  contents: read 
  pages: write 
  id-token: write 

jobs: 
  build: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Clone repository 
        uses: actions/checkout@v3 

      - name: Setup Deno environment 
        uses: denoland/setup-deno@v1 
        with: 
          deno-version: v1.x
